#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GestureSample.Droid.Resource", IsApplication=true)]

namespace GestureSample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::GestureSample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::GestureSample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Flusi1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Flusi2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Flusi3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mark_blue = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mark_red = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int O = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Pic1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Pic10 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Pic11 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Pic12 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Pic13 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Pic14 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Pic15 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Pic16 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Pic17 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Pic18 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Pic19 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Pic2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Pic20 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Pic3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Pic4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Pic5 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Pic6 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Pic7 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Pic8 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Pic9 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int X = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
